# Copyright 2017 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS-IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



runtime: python27
threadsafe: no
api_version: 1

inbound_services:
- warmup

automatic_scaling:
   min_pending_latency: 100ms
   max_pending_latency: 450ms
   min_idle_instances: 0
   max_idle_instances: 1

libraries:
- name: ssl
  version: latest
- name: PIL
  version: 1.1.7
- name: pycrypto
  version: latest
- name: webapp2
  version: latest
- name: jinja2
  version: latest

builtins:
- deferred: on

skip_files:
- ^(.*/)embedded_jdk # workaroud for rules_appengine, to prevent jdk upload

handlers:

# Warm Up handler, etc.

- url: /_ah/warmup
  script: cauliflowervest.server.main.app
  secure: always
  login: admin

# Crons.

# Disabled by default; uncomment if group_sync is implemented in your env.
# - url: /cron/group_sync
#   script: cauliflowervest.server.cron.main.app
#   secure: always
#   login: admin


# Static Files

- url: /ui/
  static_files: cauliflowervest/server/static/cv_app.html
  upload: static/cv_app.html
  login: required


- url: /static
  static_dir: cauliflowervest/server/static
  secure: always
  login: required

# Regular URL handlers.
- url: /(apple_firmware|linux_firmware|windows_firmware)/
  script: cauliflowervest.server.main.app
  secure: always
  # login requirement explicitly omitted.

- url: /(bitlocker|duplicity|filevault|luks|provisioning|xsrf-token|2xsrf-token)/.*
  script: cauliflowervest.server.main.app
  secure: always
  # login requirement explicitly omitted for OAuth2 support.


- url: /.*
  script: cauliflowervest.server.main.app
  secure: always
  login: required
